apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: schema-registry
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
